.TH URLロリ 1 urloli\-VERSION
.SH ソフト名
URLロリ - クッソ小さいURL短縮作成ソフトだわ〜♡
.SH 概要
.B urloli
[\fI\,オプション\/\fR] [\fI\,ポート番号\/\fR]
.SH 説明
.PP
URLロリはクッソ小さいURL短縮作成ソフトです。
.TP
\fB\-v\fR
バージョンを表示
.TP
\fB\-s [ポート番号]\fR
ポート番号でサーバーを開始（デフォルト＝9910）
.TP
\fB\-h\fR
ヘルプを表示
.SH 会話
.PP
XMPP: xmpp:urloli@chat.xmpp.076.ne.jp?join
.br
IRC: irc.076.ne.jp/6697 #urloli
.br
メーリングリスト: （開発中）
.SH バグ報告
.PP
バグは下記のURLまでご報告下さい：
.br
https://gitler.moe/suwako/urloli/issues
