#!/bin/sh
#
# chkconfig: 35 90 12
# description: URL Loli server
#

NAME=urloli
DESC=urloli
DAEMON=/usr/local/bin/$NAME

start () {
  echo "URLロリサーバーの開始:\n"
  sudo -u urloli /usr/local/bin/urloli &>/dev/null &
  echo
}

stop () {
  echo "URLロリサーバーの終了: \n"
  pkill urloli
  echo
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  restart|reload|condrestart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0
